### ISSUE TITLE
Reuse from Notes42 presentation?

### ISSUE THREAD

**Issue by raimondreichert** [raimondreichert/retro42-presentation#1]
- [x] a few word on pair programming?
- [x] backup slides on Wartung, Best Practices?
- [x] "stop advertisement" disclaimer? - modified
- Coffeescript primer? - no, this is about Meteor, not the programming language
- Webstorm screenshot? - no, this is about Meteor, not the IDE

**Comment by raimondreichert** [comment]
@samzurcher feel free to agree or disagree :-)

**Comment by samzurcher** [comment]
agreed - but while presenting we will have to mentioned that this is the same as last year.
